tableitem row,col 변경
jh280722/spring-resume_resume pull request #9
Opened 2021-03-11 12:44 UTC by ryuhm48

2021-03-11 13:18 UTC, jh280722 requested changes

2021-03-11 13:18 UTC, jh280722 commented on src/main/java/com/rere/item/domain/Item.java
>      }
굳이 of랑 다른 생성자랑 나눠서 만든 이유가 있을까요? 통일 해주면 좋을것 같네요

2021-03-11 13:18 UTC, jh280722 commented on src/main/java/com/rere/item/domain/Item.java
>          if (TABLE.equals(type)) {
이미지를 따로 하위로 모아서 빼는게 좋을것 같아요

2021-03-11 13:18 UTC, jh280722 commented on src/test/java/com/rere/items/ItemsTest.java
>          ));
테스트 케이스를 열심히 바꿔주셨네요 👍

2021-03-23 11:42 UTC, ryuhm48 commented
test

2021-03-23 11:44 UTC, merged